@startuml
skinparam linetype polyline
hide circle
hide stereotype


class "**Dispense**" as eD{
  EHDSMedicationDispense
  |_relatedRequest 0..*  
}


eD --> Header: "1..1"
eD --> Medication: "1..1"
eD --> Receiver: "1..1"
eD --o Dosage: "0..*"
eD --o Location: "0..1"

class "**Header**" as Header{

}

Header --> Patient: "1..1"
Header --> Dispenser: "1..1"


class "**Dispenser** (author)" as Dispenser{
  EHDSHealthProfessional   
  EHDSOrganisation
  EHDSDevice
}

class "**Patient** (subject)" as Patient{
  EHDSPatient   

}

class "**Receiver**" as Receiver{ 
  EHDSPatient
  EHDSRelatedPerson
  EHDSHealthProfessional
}

class "**DispenseLocation**" as Location{
  EHDSLocation   

}
class "**Usage Instructions**" as Dosage{
  EHDSDosaging   
 
}

class "**Medication**" as Medication{
  EHDSMedication
 
}
@enduml