@startuml
skinparam linetype polyline
hide circle
hide stereotype


class "**DispenseDecline**" as eD{
  EHDSDispenseDecline

}

eD --> Header: "1..1"
eD --> Item: "1..*"

class "**Header**" as Header{

}

Header --> Patient: "1..1"
Header --> Dispenser: "1..1"
Header --> Reason: "1..1"

class "**Dispenser** (author)" as Dispenser{
  EHDSHealthProfessional   
  
}

class "**Patient** (subject)" as Patient{
  EHDSPatient   

}

class "**Reason** (statusReason)" as Reason{
  CodeableConcept
  string

}

class "**RelatedRequest**" as Item{ 
  EHDSMedicationPrescription (item)
}


@enduml