@startmindmap
skinparam topurl StructureDefinition-

* **[[EHDSDischargeReport.html EHDSDischargeReport]]**
** Header
***_ Subject
***_ Identifier
***_ Author
***_ Date
***_ Status
***_ Language
***_ Document Type
***_ Document Title
***_ Period
***_ Version
***_ Attestation
****_ Attester
****_ Datetime
***_ Legal Authentication
****_ Legal Authenticator
****_ Datetime
***_ Event Type
***_ Service Specialty
***_ Custodian
***_ Intended Recipient
** Presented Form
** Body
*** Alerts
****_ Generated Narrative
****_ Medical Alert
*** Encounter Information
****_ Generated Narrative
****_ Encounter
****_ Note
*** Admission Evaluation
****_ Generated Narrative
****_ Objective Findings
****_ Functional Status
****_ Note
*** Patient History
****_ Generated Narrative
****_ Note
*** Course Of Encounter
****_ Generated Narrative
****_ Diagnostic Summary
****_ Procedures
****_ Medical Devices And Implants
****_ Pharmacotherapy
****_ Objective Findings
****_ Test Results
****_ Note
*** Discharge Details
****_ Generated Narrative
****_ Objective Findings
****_ Functional Status
****_ Note
*** Medication Summary
****_ Generated Narrative
****_ Medication Use
****_ Note
*** Care Plan
****_ Generated Narrative
****_ Care Plan
****_ Other Recommendations
*** Synthesis
** Attachments
@endmindmap
