@startmindmap
skinparam topurl StructureDefinition-

* [[EHDSDischargeReport.html Discharge Report]]
** Header
***_ Subject
***_ Identifier
***_ Authorship
****_ Author
****_ Datetime
***_ Last Update
***_ Status
***_ Status Reason
***_ Language
***_ Version
***_ Document Type
***_ Document Title
***_ Document Status
***_ Period
***_ Attestation
****_ Attester
****_ Datetime
***_ Legal Authentication
****_ Legal Authenticator
****_ Datetime
***_ Event Type
***_ Author Specialty
***_ Custodian
***_ Document Format
***_ Confidentiality
***_ Intended Recipient
***_ Health Insurance And Payment Information
** Presented Form
** Body
*** Advance Directives
****_ Narrative
****_ Advance Directive
*** Alerts
****_ Narrative
****_ Medical Alert
****_ Allergy And Intolerance
*** Encounter Information
****_ Narrative
****_ Encounter
*** Admission Evaluation
****_ Narrative
****_ Objective Findings
*****_ Narrative
*****_ Time
*****_ Performer
*****_ Anthropometric Observations
*****_ Vital Signs
*****_ Physical Examination
****_ Functional Status
*****_ Narrative
*****_ Functional Status Assessment
*** Patient History
****_ Narrative
****_ Medical History
*****_ Narrative
*****_ Past Problems
*****_ Devices And Implants
*****_ History Of Procedures
*****_ Vaccination
*****_ Epidemiological History
******_ Infectious Contacts
******_ Travel History
*****_ Pregnancy History
******_ Current Pregnancy Status
******_ Previous Pregnancies Status
******_ Previous Pregnancies
****_ Family History Section
*****_ Narrative
*****_ Family History
****_ Social Determinants Of Health
*****_ Narrative
*****_ Participation In Society
******_ Work Situation
******_ Hobby
******_ Social Network
*****_ Education Section
******_ Education Level
******_ Comment
*****_ Living Situation
******_ House Type
******_ Home Adaption
******_ Living Conditions
*****_ Family Situation
******_ Comment
******_ Family Composition
******_ Marital Status
******_ Number Of Children
******_ Number Of Children At Home
******_ Child Details
*******_ Living At Home
*******_ Date Of Birth
*******_ Comment
******_ Care Responsibility
*****_ Use Of Substances
******_ Narrative
******_ Alcohol Use
******_ Tobacco Use
******_ Drug Consumption
*** Course Of Encounter
****_ Diagnostic Summary
*****_ Narrative
*****_ Problem Details
******_ Present On Admission
******_ Treatment Class
******_ Problem
****_ Significant Procedures
*****_ Narrative
*****_ Procedure Entry
****_ Medical Devices And Implants
*****_ Narrative
*****_ Medical Devices And Implants
****_ Pharmacotherapy
*****_ Narrative
*****_ Pharmacotherapy
****_ Significant Observation Results
*****_ Narrative
*****_ Significant Observation Result
****_ Synthesis
*****_ Problem Synthesis
*****_ Clinical Reasoning
*** Discharge Details
****_ Narrative
****_ Objective Findings
*****_ Narrative
*****_ Anthropometric Observations
*****_ Vital Signs
*****_ Physical Examination
****_ Functional Status
*****_ Narrative
*****_ Functional Status Assessment
****_ Medication Summary
*****_ Narrative
*****_ Entry
******_ Medication Use
******_ Days Supplied
****_ Care Plan
*****_ Narrative
*****_ Care Plan
*****_ Other Recommendations
** Attachments
@endmindmap
