@startmindmap
skinparam topurl StructureDefinition-

* [[EHDSDischargeReport.html Discharge Report]]
** Discharge Report header
** Discharge Report structured body
** Presented forms
** Discharge Report attachments
@endmindmap