@startmindmap
skinparam topurl StructureDefinition-
* [[EHDSHospitalDischargeReportHeader.html Hospital Discharge Report Header]]
** Subject
** Related person
** Preferred Health Professional
** Health insurance and payment information
** Intended recipient
** Authorship
***_ Author
***_ DateTime
** Attestation
***_ Attester
***_ DateTime
** Legal authentication
***_ Legal authenticator
***_ DateTime
** Document metadata
***_ Document ID
***_ Document type
***_ Document status
***_ Period
***_ Report date and time
***_ Document title
***_ Event type
***_ Specialty
***_ Report custodian
***_ Document format
***_ Confidentiality
***_ Language
***_ Version
/' ** Knowledge resources
***_ External reference
***_ Related with
 '/
 @endmindmap