PlantUML

@startmindmap
skinparam topurl StructureDefinition-
* [[EHDSHospitalDischargeReportBody.html Hospital Discharge Report body]]
** Advance directives
***_ Living will
***_ Date and time
***_ Type
***_ Comment
***_ Related conditions
***_ Living will document
** Alerts section
***_ Section narrative
***_ Allergy and Intolerance
***_ Medical alerts
** Encounter information section
***_ Section narrative
***_ Priority
***_ Admitting facility (Service provider)
***_ Actual encounter period
***_ Admission information
****_ Admitter
****_ Admit Source
****_ Referring professional
****_ Admission Reason
****_ Admission legal status
***_ Discharge information
****_ Destination type
****_ Destination location
***_ Location
****_ Period
****_ Organization part

** Admission evaluation
***_ Section narrative
***_ Objective findings
****_ Date and time
****_ Performer
****_ Section narrative
****_ Anthropometric observations
****_ Vital signs
****_ Physical examination
***_ Functional status
****_ Date and time
****_ Performer
****_ Section narrative
****_ Functional status assessment
** Patient history
***_ Section narrative
***_ Medical history
****_ Section narrative
****_ Past problems
****_ Devices and implants
****_ History of procedures
****_ Vaccination
****_ Epidemiological history
***_ Family history
***_ Social determinants of health
***_ Use of substances
** Course of hospitalisation (Hospital stay)
***_ Section narrative
***_ Diagnostic summary
***_ Significant procedures
***_ Medical devices and implants
***_ Pharmacotherapy
***_ Significant Observation Results
***_ Synthesis
** Discharge details
***_ Section narrative
***_ Objective findings
****_ Date and time
****_ Performer
****_ Section narrative
****_ Anthropometric observations
****_ Vital signs
****_ Physical examination
***_ Functional status
****_ Date and time
****_ Performer
****_ Section narrative
****_ Functional status assessment
** Medication summary
** Care plan
***_ Title
***_ Addresses
***_ Care plan description
***_ Other recommendations
@endmindmap