PlantUML

@startmindmap
skinparam topurl StructureDefinition-
* [[EHDSHospitalDischargeReportBody.html Hospital Discharge Report body]]
** Advance directives
***_ Living will
***_ Date and time
***_ Type
***_ Comment
***_ Related conditions
***_ Living will document
** Alerts section
***_ Section narrative
***_ Allergy and Intolerance
***_ Medical alerts
** Encounter information section
***_ Section narrative
***_ Encounter information section
** Admission evaluation
***_ Section narrative
***_ Objective findings
****_ Date and time
****_ Performer
****_ Section narrative
****_ Anthropometric obsevations
****_ Vital signs
****_ Physical examination
***_ Functional status
****_ Date and time
****_ Performer
****_ Section narrative
****_ Functional status assessment
** Patient history
***_ Section narrative
***_ Medical history
****_ Section narrative
****_ Past problems
@endmindmap