PlantUML

@startmindmap
skinparam topurl StructureDefinition-
* [[EHDSHospitalDischargeReportBody.html Hospital Discharge Report body]]
** Advance directives
***_ Living will
***_ Date and time
***_ Type
***_ Comment
***_ Related conditions
***_ Living will document
** Alerts section
***_ Section narrative
***_ Allergy and Intolerance
***_ Medical alerts
** Encounter information section
***_ Section narrative
***_ Priority
***_ Admitting facility (Service provider)
***_ Actual encounter period
***_ Admission information
****_ Admitter
****_ Admit Source
****_ Referring professional
****_ Admission Reason
****_ Admission legal status
***_ Discharge information
****_ Destination type
****_ Destination location
***_ Location
****_ Period
****_ Organization part

** Admission evaluation
***_ Section narrative
***_ Objective findings
****_ Date and time
****_ Performer
****_ Section narrative
****_ Anthropometric observations
****_ Vital signs
****_ Physical examination
***_ Functional status
****_ Date and time
****_ Performer
****_ Section narrative
****_ Functional status assessment
** Patient history
***_ Section narrative
***_ Medical history
****_ Section narrative
****_ Past problems
****_ Devices and implants
****_ History of procedures
****_ Vaccination
****_ Epidemiological history
***_ Family history
***_ Social determinants of health
***_ Use of substances
** Course of hospitalisation (Hospital stay)
***_ Section narrative
***_ Diagnostic summary
***_ Significant procedures
***_ Medical devices and implants
***_ Pharmacotherapy
***_ Significant Observation Results
***_ Synthesis
** Discharge details
***_ Section narrative
***_ Objective findings
****_ Date and time
****_ Performer
****_ Section narrative
****_ Anthropometric observations
****_ Vital signs
****_ Physical examination
***_ Functional status
****_ Date and time
****_ Performer
****_ Section narrative
****_ Functional status assessment
** Medication summary
** Care plan
***_ Title
***_ Addresses
***_ Care plan description
***_ Other recommendations
@endmindmap


@startmindmap
skinparam topurl StructureDefinition-
* [[EHDSHospitalDischargeReportBody.html Hospital Discharge Report body]]
** Advance directives
***_ Living will
***_ Date and time
***_ Type
***_ Comment
***_ Related conditions
***_ Living will document
** Alerts section
***_ Section narative
***_ Allergy and Intolerance
***_ Medical alerts
** Encounter information section
***_ Section narative
***_ Encounter information section
** Admission evaluation
***_ Section narative
***_ Objective findings
****_ Date and time
****_ Performer
****_ Section narative
****_ Anthropometric observations
****_ Vital signs
****_ Physical examination
***_ Functional status
****_ Date and time
****_ Performer
****_ Section narative
****_ Functional status assessment
** Patient history
***_ Section narative
***_ Medical history
****_ Sub-section narative
****_ Past problems
****_ Devices and Implants
****_ History of procedures
****_ Vaccination
****_ Epidemiological history
*****_ Infectious contacts
******_ Time period
******_ Infectious agent
******_ Proximity
******_ Country
******_ Additional information
*****_ Travel history
******_ Time period
******_ Country visited
******_ Comment
***_ Family history section
****_ Sub-section narative
****_ Family history
***_ Social determinants of health
****_ Sub-section narative
****_ Participation in society
*****_ Work situation
*****_ Hobby
*****_ Social network
****_ Education section
*****_ Education level
*****_ Comment
****_ Living situation
*****_ House type
*****_ Home adaption
*****_ Living conditions
****_ Family situation
*****_ Comment
*****_ Family composition
*****_ Marital status
*****_ Number of children
*****_ Number of children at home
*****_ Child details
******_ Living at home
******_ Date of Birth
******_ Comment
*****_ Care responsibility
***_ Use of substances
****_ Sub-section narative
****_ Alcohol use
*****_ Status
*****_ Period and quantity
******_ Period
******_ Quantity
*****_ Comment
****_ Tobacco use
*****_ Status
*****_ Period and quantity
******_ Period
******_ Quantity
*****_ Comment
****_ Drug consumption
*****_ Status
*****_ Period and quantity
******_ Period
******_ Quantity
******_ Drug or medication type
******_ Route of administration
*****_ Coment
** Course of hospitalisation
***_ Diagnostic summary
****_ Problem description
****_ Problem details
***_ Significant procedures
****_ Sub-section narative
****_ Procedure entry
***_ Medical devices and implants section
****_ Sub-section narative
****_ Medical devices and implants
***_ Pharmacotherapy section
****_ Sub-section narative
****_ Pharmacotherapy
***_ Significant Observation Results
****_ Sub-section narative
****_ Significant Observation Result
***_ Synthesis
****_ Problem synthesis
****_ Clinical reasoning
** Discharge details
***_ Section narative
***_ Objective findings
****_ Date and time
****_ Performer
****_ Section narative
****_ Anthropometric observations
****_ Vital signs
****_ Physical examination
***_ Functional status
****_ Date and time
****_ Performer
****_ Section narative
****_ Functional status assessment
** Medication summary
***_ Section narative
***_ Medication details
** Care plan and other recommendations after discharge.
***_ Section narative
***_ Care plan
***_ Other recommendations
@endmindmap