@startmindmap
skinparam topurl StructureDefinition-

* [[EHDSHospitalDischargeReport.html Hospital Discharge Report]]
** Hospital Discharge Report header
** Hospital Discharge Report structured body
** Presented forms
** Hospital Discharge Report attachments
@endmindmap