@startmindmap
skinparam topurl StructureDefinition-

* **[[EHDSImagingStudy.html EHDSImagingStudy]]**
** Header
***_ Subject
***_ Identifier
***_ Author
***_ Date
***_ Status
***_ Language
** Modality
** Body Site
** Encounter
** Started
** Based On
** Number Of Series
** Number Of Instances
** Description
** Study Custodian
** Study Endpoint
** Series
***_ Series Uid
***_ Number
***_ Series Modality
***_ Description
***_ Number Of Instances
***_ Series Endpoint
***_ Body Site
***_ Specimen
***_ Started
***_ Instances In The Series
****_ Instance Title
****_ Instance Uid
****_ Sop Class
****_ Instance Number
****_ Number Of Frames
****_ Key Image
*****_ Flag
*****_ Reason
*****_ SeriesUID
*****_ InstanceUID
@endmindmap
