@startmindmap
* EHDSImagingStudy
** Header
***_ Subject
***_ Identifier
***_ Authorship
****_ Author
****_ Datetime
***_ Last Update
***_ Status
***_ Status Reason
***_ Language
** Modality
** Encounter
** Started
** Based On
** Number Of Series
** Number Of Instances
** Description
** Study Custodian
** Study Endpoint
** Series
***_ Series Uid
***_ Number
***_ Acquisition Modality
***_ Description
***_ Number Of Instances
***_ Series Endpoint
***_ Body Site
***_ Specimen
***_ Started
***_ Instances In The Series
****_ Instance Title
****_ Instance Uid
****_ Sop Class
****_ Instance Number
****_ Number Of Frames
@endmindmap