@startmindmap
skinparam topurl StructureDefinition-

* [[EHDSImagingReport.html Imaging Report body]]
** Order information
***_ Order Id
***_ Order date and time
***_ Order placer
***_ Order reason text
***_ Order reason
***_ Clinical question
***_ Supporting information
****_ Observation
****_ Condition
****_ Medication Administration
****_ Devices
****_ Pregnancy status
****_ Gestational age
****_ Sex for clinical use
****_ Other supporting information
** Specimen
** Service request
** Exposure information
***_ Effective dose
***_ Equivalent dose information
****_ Equivalent dose
****_ Tissue type
** Examination Report
***_ Modality
***_ Body part
****_ Body location
****_ Laterality
***_ Imaging procedures
***_ Medication
***_ Adverse reaction
***_ Result data
****_ Result text
****_ Observation results
***_ Conclusion
****_ Impression
****_ Condition or finding
** Recommendation
***_ Description
***_ Care plan
** Comparison Study
@endmindmap