@startmindmap
skinparam topurl StructureDefinition-

* **[[EHDSImagingReport.html EHDSImagingReport]]**
** Header
***_ Subject
***_ Identifier
***_ Author
***_ Date
***_ Status
***_ Language
***_ Document Type
***_ Document Title
***_ Period
***_ Version
***_ Attestation
****_ Attester
****_ Datetime
***_ Legal Authentication
****_ Legal Authenticator
****_ Datetime
***_ Event Type
***_ Service Specialty
***_ Custodian
***_ Accession Number
***_ Intended Recipient
** Presented Form
** Body
*** Order Information
****_ Order Id
****_ Order Date And Time
****_ Order Placer
****_ Order Reason
****_ Clinical Question
*** Supporting Information
****_ Observation
****_ Condition
****_ Prior Medication Administration
****_ Device
****_ Pregnancy Status
****_ Sex For Clinical Use
*** Specimen
*** Service Request
*** Exposure Information
*** Examination Report
****_ Modality
****_ Body Site
****_ Imaging Procedures
****_ Medication Administration
****_ Adverse Reaction
****_ Results
****_ Conclusion
*****_ Impression
*****_ Condition Or Finding
*** Recommendation
****_ Description
****_ Care Plan
*** Comparison Study
** Dicom Study Metadata
** Attachments
@endmindmap
