@startmindmap
* EHDSImagingReport
** Header
***_ Subject
***_ Identifier
***_ Authorship
****_ Author
****_ Datetime
***_ Last Update
***_ Status
***_ Status Reason
***_ Language
***_ Document Type
***_ Document Title
***_ Period
***_ Version
***_ Attestation
****_ Attester
****_ Datetime
***_ Legal Authentication
****_ Legal Authenticator
****_ Datetime
***_ Event Type
***_ Service Specialty
***_ Custodian
***_ Confidentiality
***_ Accession Number
***_ Health Insurance And Payment Information
***_ Intended Recipient
** Body
***_ Order Information
****_ Order Id
****_ Order Date And Time
****_ Order Placer
****_ Order Reason Text
****_ Order Reason
****_ Clinical Question
***_ Supporting Information
****_ Observation
****_ Condition
****_ Medication Administration
****_ Devices
****_ Pregnancy Status
****_ Sex For Clinical Use
****_ Other Supporting Information
***_ Specimen
***_ Service Request
***_ Exposure Information
****_ Effective Dose
****_ Equivalent Dose Information
*****_ Equivalent Dose
*****_ Tissue Type
***_ Examination Report
****_ Modality
****_ Body Part
****_ Imaging Procedures
****_ Medication
****_ Adverse Reaction
****_ Result Data
*****_ Result Text
*****_ Observation Results
****_ Conclusion
*****_ Impression
*****_ Condition Or Finding
***_ Recommendation
****_ Description
****_ Care Plan
***_ Comparison Study
** Presented Form
** Dicom Study Metadata
** Attachments
@endmindmap