@startuml
"Medical Test Result Creator" as creator
"Medical Test Result Repository" as repos
"Medical Test Result Consumer" as consumer
"Generate a report" as (create)
"Store a report" as (store)
"Use a report" as (use)
"Send/Provide a report" as (send)
"Receive/Query a report" as (receive)

creator --> (create)
creator --> (send)
consumer --> (use)
consumer --> (receive)
repos --> (store)
repos --> (send)
repos --> (receive)
@enduml