@startmindmap
skinparam topurl StructureDefinition-

* [[EHDSLaboratoryOrder.html Laboratory Order]]
** Laboratory Order header
** Laboratory Order structured body
** Presented forms
** Laboratory Order attachments
@endmindmap


[[index PlantUML website]]