@startuml
skinparam linetype polyline
hide circle
hide stereotype


class "**Laboratory report**" as labReport{
  Laboratory Report Header
  Laboratory Report Body
  Presented Form
  Media
}

labReport *--> header: "1..1"
labReport *--> body: "1..1"
labReport *--> presentedForm: "0..1"
labReport *--> media: "0..*"

class "**Laboratory Report Header**" as header{
  subject 1..1
  healthInsuranceAndPaymentInformation 0..1
  intendedRecipient 0..*
  authorization 1..*
  attestation 0..*
  legalAuthentication 0..1
  documentMetadata 1..1
}

class "**Laboratory Report Body**" as body{
}

body *--> orderInformation: "0..*"
body *--> specimen: "0..*"
body *--> resultData: "1..1"

class "**Order information**" as orderInformation {

}

class "**Specimen**" as specimen {

}

class "**Result data**" as resultData {
  Narrative Report 0..1
  Comments Interpretations and Recommendations 0..*
  Test Results
}

resultData *--> results: 0..*

class "**Test Results**" as results {
  Narrative Report
  Comments Interpretations and Recommendations
  Test Results
}


class "**Presented Form**" as presentedForm {
  Attachment
}

class "**Media**" as media {
  Attachment
}


@enduml