@startmindmap
skinparam topurl StructureDefinition-
* [[EHDSLaboratoryOrderBody.html Laboratory Order body]]
** Order information
***_ Order Id
***_ Order date and time
***_ Order text
***_ Order placer
***_ Order reason text
***_ Order reason
** Encounter
** Supporting information
***_ Observation
***_ Condition
***_ Medication Administration
***_ Sex for clinical use
***_ Vaccination
***_ Other supporting information
** Specimen
** Service requests
** Allergy
** Alerts
** Appointment
@endmindmap
