@startmindmap
* Laboratory Order Body
** Order information
***_ Order Id
***_ Order date and time
***_ Order urgency
***_ Order placer
***_ Order reason text
***_ Order reason
** Supporting information
***_ Observation
***_ Condition
***_ Medication administration
***_ Sex for clinical use
** Allergy
** Allerts
** Encounter
***_ Encounter Id
***_ Encounter type
***_ Encounter details
** Reimbursement information
** Service requests
** Specimen
***_ Specimen type
***_ Collection information
***_ Container information
** Scheduling information
@endmindmap