@startmindmap
skinparam topurl StructureDefinition-
* [[EHDSLaboratoryReport.html Laboratory Report Body]]
** Order information
***_ Order Id
***_ Order date and time
***_ Order placer
***_ Order reason text
***_ Order reason
***_ Clinical question
** Supporting information
***_ Observation
***_ Condition
***_ Medication Administration
***_ Sex for clinical use
***_ Service requests
** Specimen
** Result data
***_ Narrative report
***_ Comments interpretations and recommendations
***_ Laboratory test results
@endmindmap