@startmindmap
skinparam topurl StructureDefinition-

* **[[EHDSLaboratoryReport.html EHDSLaboratoryReport]]**
** Header
***_ Subject
***_ Identifier
***_ Author
***_ Date
***_ Status
***_ Language
***_ Document Type
***_ Document Title
***_ Period
***_ Version
***_ Attestation
****_ Attester
****_ Datetime
***_ Legal Authentication
****_ Legal Authenticator
****_ Datetime
***_ Event Type
***_ Service Specialty
***_ Custodian
** Presented Form
** Intended Recipient
** Body
*** Order Information
****_ Order Id
****_ Order Date And Time
****_ Order Placer
****_ Order Reason Text
****_ Order Reason
****_ Clinical Question
*** Supporting Information
****_ Observation
****_ Condition
****_ Medication Administration
****_ Sex For Clinical Use
****_ Vaccination
****_ Other Supporting Information
*** Specimen
*** Service Request
*** Result Data
****_ Comments Interpretation And Recommendations
****_ Laboratory Test Results
** Attachments
@endmindmap
