@startmindmap
skinparam topurl StructureDefinition-

* **EHDS Laboratory Report**
** Header (document metadata)
** Body
*** Order Information
****_ Order Placer
****_ Order Reason
****_ Clinical Question
*** Supporting Information
*** Specimen
*** Service Request
*** Result Data
**** Laboratory Test Results
**** Comments Interpretation And Recommendations
** Presented Form
** Attachments
@endmindmap
