@startmindmap
skinparam topurl StructureDefinition-

* **[[EHDSPatientSummary.html EHDSPatientSummary]]**
** Header
***_ Subject
***_ Identifier
***_ Author
***_ Date
***_ Status
***_ Language
***_ Document Type
***_ Document Title
***_ Period
***_ Version
***_ Attestation
****_ Attester
****_ Datetime
***_ Legal Authentication
****_ Legal Authenticator
****_ Datetime
***_ Event Type
***_ Service Specialty
***_ Custodian
** Presented Form
** Alerts
***_ Generated Narrative
***_ Empty Reason
***_ Medical Alert
***_ Note
** Allergies And Intolerances
***_ Generated Narrative
***_ Allergy Intolerance
***_ Empty Reason
***_ Note
** Problems
***_ Generated Narrative
***_ Empty Reason
***_ Problem
***_ Note
** Medication Summary
***_ Generated Narrative
***_ Empty Reason
***_ Medication Use
***_ Note
** Medical Devices And Implants
***_ Generated Narrative
***_ Empty Reason
***_ Device Use
***_ Note
** Procedures
***_ Generated Narrative
***_ Empty Reason
***_ Procedure
***_ Note
** Immunisations
***_ Generated Narrative
***_ Immunisation
***_ Note
** Functional Status
***_ Generated Narrative
***_ Condition
***_ Assessment
***_ Note
** Social History
***_ Generated Narrative
***_ Observation
***_ Note
** Pregnancy History
***_ Generated Narrative
***_ Current Pregnancy Status
***_ Previous Pregnancies
***_ Note
** Travel History
***_ Generated Narrative
***_ Travel History
***_ Note
** Patient Story
***_ Note
** Advance Directives
***_ Generated Narrative
***_ Advance Directive
***_ Note
** Observation Results
***_ Generated Narrative
***_ Result
***_ Note
** Care Plans
***_ Generated Narrative
***_ Care Plan
***_ Note
@endmindmap
