@startmindmap
skinparam topurl StructureDefinition-

* **[[EHDSMedicationPrescription.html EHDSMedicationPrescription]]**
** Header
***_ Subject
***_ Identifier
***_ Author
***_ Date
***_ Status
***_ Language
***_ Status Reason
** Presented Form
** Prescription Item
***_ Identifier
***_ Status
***_ Status Reason
***_ Medication
***_ Indication
***_ Intended Use Type
***_ Period Of Use
***_ Quantity Prescribed
***_ Dosage Instructions
***_ Validity Period
***_ Substitution
****_ Allowed
****_ Reason
***_ Number Of Repeats
***_ Minimum Dispense Interval
***_ Off Label
****_ Is Off Label Use
****_ Reason
***_ Note
@endmindmap
