@startuml
skinparam linetype polyline
hide circle
hide stereotype


class "**Prescription**" as eP{
  EHDSMedicationPrescription 
}

eP --> Header: "1..1"
eP --o Item: "1..*"
eP --o PresentedForm: "0..*"

class "**Prescriber** (author)" as Prescriber{
  EHDSHealthProfessional   
  
}

class "**Patient** (subject)" as Patient{
  EHDSPatient   

}

class "**PrescriptionHeader**" as Header{
  EHDSMedicationPrescriptionHeader   

}

Header --> Prescriber: "1..1"
Header --> Patient: "1..1"


class "**PrescriptionItem**" as Item{ 
}

Item --> Medication: "1..1"
Item --o Dosage: "0..*"


class "**DosageInstructions**" as Dosage{
  EHDSDosaging   
 
}

class "**Medication**" as Medication{
  EHDSMedication
 
}

class "**PresentedForm**" as PresentedForm{
  EHDSAttachment   
 
}
@enduml