@startuml
skinparam linetype polyline
hide circle
hide stereotype


class "**Prescription**" as eP{
  EHDSMedicationPrescription 
}

eP --> Header: "1..1"
eP --o Item: "1..*"
eP --o PresentedForm: "0..*"

class "**Prescriber** (author)" as Prescriber{
  EHDSHealthProfessional   
  EHDSOrgnisation
}

class "**Patient** (subject)" as Patient{
  EHDSPatient   

}

class "**Header**" as Header{
     

}

Header --> Prescriber: "1..*"
Header --> Patient: "1..1"


class "**PrescriptionItem**" as Item{ 
}

Item --> Medication: "1..1"
Item --o Dosage: "1..1"


class "**DosageInstructions**" as Dosage{
  EHDSDosage   
 
}

class "**Medication**" as Medication{
  EHDSMedication
 
}

class "**PresentedForm**" as PresentedForm{
  EHDSAttachment   
 
}
@enduml