@startmindmap
* Prescription
** Identifier
** Prescriber
** Issue Date
** Patient
** Category
** Valid From
** Valid Until
** Recorder
** Recording Date
** Status
** Status Reason
** Status Reason Text
** Dispensable
** Comment
** Prescription Item
*** Identifier
*** Medication
*** Indication
*** Indication Text
*** Prescription Intent
*** Treatment Period
*** Quantity Prescribed
*** Dosage Instructions
*** Preparation Instructions
*** Substitution
**** Allowed
**** Type
**** Type Reason
*** Status
*** Status Reason
*** Status Reason Text
*** Reason For Change
*** Repeats Allowed
*** Comment
@endmindmap