@startmindmap
* Dosage
** Sequence
** Text
** Additional Instruction
** Patient Instruction
** Dose And Rate
*** Type
*** Dose
*** Rate
** Timing
*** Event
*** Code
*** Repeat
**** Bounds
***** Duration
***** Range
***** Period
**** Count
***** Count
***** Count Max
**** Duration
***** Duration
***** Duration Max
**** Frequency
***** Number Of Times
***** Max Number Of Times
***** Period
***** Period Max
**** Day Of Week
**** Time Of Day
**** Event Time
***** When
***** Offset
** As Needed
** As Needed For
** Body Site
** Route Of Administration
** Method Of Administration
** Max Dose
*** Max Dose Per Period
*** Max Dose Per Administration
*** Max Dose Per Lifetime
@endmindmap