@startmindmap
* Medicinal Product
** Identifying Code
** Classification
** Product Name
** Marketing Authorisation Holder
*** Organization Name
*** Organization Identifier
** Dose Form
** Pack Size
** Item
*** Dose Form
*** Ingredient
**** Is Active
**** Substance
**** Strength Info
***** Strength
***** Strength Type
***** Strength Substance
*** Unit Of Presentation
*** Contained Quantity
*** Amount
*** Package Type
** Device
*** Device Quantity
*** Device
** Characteristic
*** Type
*** Value
** Additional Product Information
@endmindmap