@startmindmap
* Dispense
** Identifier
** Patient
** Receiver
** Dispenser
** Related Request
** Medication
** Dispensed Quantity
** Time Of Dispensation
** Substitution
*** Substitution Occurred
*** Substitution Type
*** Substitution Reason
** Status
** Status Reason
** Status Reason Text
** Dosage Instructions
** Comment
@endmindmap