@startuml
skinparam linetype polyline
hide circle
hide stereotype


class "**Prescription**" as eP{
  EHDSMedicationPrescription 
}

eP --> Patient: "1..1"
eP --> Prescriber: "1..1"
eP --o Item: "1..*"

class "**Prescriber**" as Prescriber{
  EHDSHealthProfessional   
  
}

class "**Patient**" as Patient{
  EHDSPatient   

}

class "**PrescriptionItem**" as Item{ 
}

Item --> Medication: "1..1"
Item --o Dosage: "0..*"


class "**Usage Instructions**" as Dosage{
  EHDSDosaging   
 
}

class "**Medication**" as Medication{
  EHDSMedication
 
}
@enduml