@startmindmap
skinparam topurl StructureDefinition-

* **[[EHDSMedicationDispense.html EHDSMedicationDispense]]**
** Header
***_ Subject
***_ Identifier
***_ Author
***_ Date
***_ Status
***_ Language
** Dispense Location
** Receiver
** Related Request
** Medication
** Dispensed Quantity
** Time Of Dispensation
** Substitution Occurred
** Dosage Instructions
** Note
@endmindmap
