@startmindmap
* Patient Summary
** Patient Summary header
** Patient Summary body
*** Alerts
**** Allergy
**** Medical alert
*** Medical history
**** Vaccination
**** Past problems
**** Medical history
*** Medical problems
**** Current problems
**** Medical devices and implants
**** Procedures
**** Functional status
*** Medication summary 
@endmindmap