@startmindmap
skinparam topurl StructureDefinition-
* [[EHDSPatientSummary.html Patient Summary]]
** Patient Summary header
** Presented forms
** Knowledge resources
** Preferred health professional
** Alerts
** Allergies and intolerances
** Medical history
** Immunisations
** Current problems
** Medical devices and implants
** Procedures
** Medication summary
** Functional status
** Social history
** Pregnancy history
*** Current pregnancy status
*** Previous pregnancies
** Patient provided data
*** Travel history
** Advance directives
** Results
** Care plan
@endmindmap