@startmindmap
* Patient Summary header
** Subject
** Related person
** Preferred Health Professional
** Authorship
***_ Author
***_ DateTime
** Document metadata
***_ Document ID
***_ Document type
***_ Document status
***_ Period
***_ Report date and time
***_ Document title
***_ Report custodian
***_ Document format
***_ Confidentiality
***_ Language
***_ Version
***_ Date of last update
***_ Nature of the document
** Additional information / Knowledge resources
***_ External reference
***_ Related with
@endmindmap