.@startmindmap
skinparam topurl StructureDefinition-
* [[EHDSPatientSummary.html Patient Summary]]
** Header
***_ Subject
***_ Identifier
***_ Authorship
****_ Author
****_ Datetime
***_ Last Update
***_ Status
***_ Status Reason
***_ Language
***_ Document Type
***_ Document Title
***_ Period
***_ Version
***_ Attestation
****_ Attester
****_ Datetime
***_ Legal Authentication
****_ Legal Authenticator
****_ Datetime
***_ Event Type
***_ Service Specialty
***_ Custodian
***_ Confidentiality
** Presented Form
** Alerts
***_ Narrative
***_ Empty Reason
***_ Medical Alert
** Allergies And Intolerances
***_ Narrative
***_ Allergy Intolerance
***_ Empty Reason
** Problems
***_ Narrative
***_ Empty Reason
***_ Problems
** Medication Summary
***_ Narrative
***_ Empty Reason
***_ Medication Treatment
** Medical Devices And Implants
***_ Narrative
***_ Empty Reason
***_ Medical Device
** Procedures
***_ Narrative
***_ Empty Reason
***_ Procedure
** Vaccination
***_ Narrative
***_ Vaccination
** Functional Status
***_ Narrative
***_ Functional Status Assessment
** Social History
***_ Narrative
***_ Social History Observation
** Pregnancy History
***_ Generated Narrative
***_ Current Pregnancy Status
***_ Previous Pregnancies Status
***_ Previous Pregnancies
** Travel History
***_ Narrative
***_ Travel History
** Patient Story
***_ Narrative
** Advance Directives
***_ Narrative
***_ Advance Directive
** Results
***_ Narrative
***_ Result Observation
** Care Plan
***_ Narrative
***_ Care Plan Entry
@endmindmap
