@startmindmap PsReportBody_CIM
skinparam topurl StructureDefinition-
* [[EHDSPatientSummaryBody.html Patient summary body]]
** Alerts
***_ Section narative
***_ Allergy
***_ Medical alert
** Medical history
***_ Section narative
***_ Vaccination section
****_ Subsection narative
****_ Vaccination
***_ Past problems section
****_ Subsection narative
****_ Past problems
***_ Medical history section
****_ Medical history
** Medical problems
***_ Section narative
***_ Current problems section
****_ Subsection narative
****_ Current problems
***_ Medical devices and implants section
****_ Subsection narative
****_ Medical devices and implants
***_ Procedures section
****_ Subsection narative
****_ Procedures
***_ Functional status section
****_ Subsection narative
****_ Functional status assessment
** Medication summary
***_ Section narative
***_ Current and relevant past medicines
** Social history
***_ Social history description
***_ Social history observations related to health
****_ Reference date range
** Pregnancy history
***_ Section narative
***_ Current pregnancy status
****_ Date of observation
****_ Status
****_ Expected date of delivery
***_ History of previous pregnancies
****_ Previous pregnancies status
****_ Previous pregnancies description
*****_ Outcome date
*****_ Outcome
*****_ Number of children
** Patient provided data
***_ Section narative
***_ Travel history
****_ Country
****_ Period
***_ Advance Directive
****_ Documentation
** Results
***_ Section narative
***_ Result observation
** Plan of Care
***_ Description
***_ Plan of Care Entry
@endmindmap