@startuml
'skinparam linetype polyline
'
hide circle
hide stereotype
hide methods
'hide attributes

class "**CommonHeader**" as H {
  |_ Subject 0..1
  |_ Authorship 1..*
    |_ Author 1..1
    |_ DateTime 0..1
  |_ LastUpdateDateTime
  |_ Attestation 0..*
    |_ Attester 1..1
    |_ DateTime 1..1 
  |_ LegalAuthentication 0..1  
    |_ Authenticator 1..1
    |_ DateTime 1..1 
  |_ Status
  |_ Language
  |_ Version
}


class "**Subject**" as S {

}

class "**DocumentHeader**" as DH {
  |_ DocumentId 1..*
  |_ DocumentType 1..1
  |_ DocumentTitle 0..1
  |_ EventType (Tags, labels) 0..*   
  |_ Period 0..1 
  |_ ReportDateTime 1..1
  |_ DocumentStatus
  |_ Specialty 0..* (authorSpecialty) 
  |_ ReportCustodian 1..1
  |_ DocumentFormat 0..1
  |_ Confidentiality 0..1 (Why? Really, why???)  
  |_ Language
  |_ NatureOfTheDocument (IPS)
  |_ KnowledgeResources (0..*)
    |_ ExternalReferences
    |_ RelatedWith
  |_ ComparableStudies
}


class "**Report**" as R {
  |_ PresentedForm 0..*   
  |_ ReportBody 0..1   
  |_ ReportAttachments 0..*   
  |_ OrderId 0..1
}



class ReportBody {
  |_ PresentedForm 0..*   
  |_ ReportBody 0..1   
  |_ ReportAttachments 0..*   (what about key images, priot images)
  |_ OrderId 0..1 

}



class "**LaboratoryReport**" as LR {
  ' |_ PresentedForm 0..*   
  ' |_ ReportBody 0..1   
  ' |_ ReportAttachments 0..*   
  ' |_ OrderId 0..1
}



class "**ImagingReport**" as IR {
  |_ ImagingStudy 1..1 ??
  |_ ComparisonStudy
}



LR -u-|> R
IR -u-|> R

LR -u- DH

S <--l-- H

DH --u--|> H 

class "**AdministrativeInformation**" as AdministrativeInformation {
  |_ RelatedPerson 0..*
  |_ PreferredHP 0..*
  |_ InsuranceCoverage 0..*

}

class "**ePrescription**" as EP {
  
}

EP *-u- H
EP *.u. DH #F22: ??? \n No, \nwe don't\nwant this


PS *-u- DH


class "**EHDSAttachment**" as EHDSAttachment {
  |_ contentType 0..1   
  |_ language 0..1   
  |_ data 0..1   
  |_ url 0..1   
  |_ size 0..1   
  |_ hash 0..1   
  |_ title 0..1   
  |_ creationDate 0..1   
}




' class "**DocumentMetadata**" as DocumentMetadata {
' }



' class "**EHDSReportHeader**" as EHDSReportHeader {
' }


' class "**EHDSLaboratoryReport**" as EHDSLaboratoryReport {
'   |_ laboratoryReportHeader 1..1   
'   |_ laboratoryReportBody 1..1   
'   |_ laboratoryReportAttachments 0..1   
' }


' class "**EHDSLaboratoryReportHeader**" as EHDSLaboratoryReportHeader {
' }




class "**PatientSummary**" as PS {
  
}



class "**HospitalDischargeReport**" as DR {

}



class "**EHDSLaboratoryReportBody**" as EHDSLaboratoryReportBody {
  |_ orderInformation 0..*   
    |_ **clinicalQuestion 0..1**
  |_ supportingInformation 0..*   
'    |_ observation 0..*   
'    |_ condition 0..*   
'    |_ medicationAdministration 0..*   
'    |_ sexForClinicalUse 0..*
'    |_ otherSupportingInformation 0..*   
'    |_ pregnancystatus
    |_ --gestationalAge--
    |_ --devices--
  |_ specimen 0..*   
  |_ serviceRequest 0..*   
  |_ resultData 1..1   
    |_ narrativeReport 0..1   
    |_ commentsInterpretationAndRecommendations 0..*   
    |_ laboratoryTestResults 0..*   
}

EHDSLaboratoryReportBody -u-> LR



' class "**EHDSImagingReportHeader**" as EHDSImagingReportHeader {

' }

' class "**EHDSImagingReportBody**" as EHDSImagingReportBody {
'   |_ specimen 0..*   
'   |_ serviceRequest 0..*   
'   |_ exposureInformation 0..1   
'     |_ effectiveDose 0..*   
'     |_ equivalentDoseInformation 1..1   
'       |_ equivalentDose 1..1   
'       |_ tissueType 1..1   
'   |_ examinationReport 1..1   
'     |_ modality 1..*   
'     |_ bodyPart 0..*   
'       |_ bodyLocation 0..1   
'       |_ laterality 0..1   
'     |_ imagingProcedures 0..*   
'     |_ medication 0..*   
'     |_ adverseReaction 0..*   
'     |_ resultData 0..1   
'       |_ resultText 1..1   
'       |_ observationResults 0..*   
'     |_ conclusion 1..1   
'       |_ impression 1..1   
'       |_ codedConclusion 0..1   
'         |_ condition 0..*   
'   |_ recommendation 0..1   
'     |_ description 1..1   
'     |_ carePlan 0..*   
'   |_ comparisonStudy 0..*   
' }

' class "**EHDSImagingReport**" as IR2 {
'   |_ imagingReportHeader 1..1   
'   |_ imagingReportBody 1..1   
'   |_ imagingReportAttachments 0..1   
' }


' class "**ImagingReportDocumentMetadata**" as ImgReportDocumentMetadata {
'   |_ studyInstanceUid 0..*   
'   |_ accessionNumber 0..1   
' }


' class "**OrderInformation**" as OrderInformation {
'     |_ orderId 1..*   
'     |_ orderDateAndTime 0..1   
'     |_ orderPlacer 0..1   
'     |_ orderReasonText 0..*   
'     |_ orderReason 0..*   
'     |_ clinicalQuestion 0..1   
'     |_ supportingInformation 0..*   
'       |_ observation 0..*   
'       |_ condition 0..*   
'       |_ medicationAdministration 0..*   
'       |_ devices 0..*   
'       |_ pregnancyStatus 0..1   
'       |_ gestationalAge 0..1   
'       |_ sexForClinicalUse 0..*   
'       |_ otherSupportingInformation 0..*     
'   }


' class "**ContentMetadata**" as ContentMetadata {
'   |_ subject 1..1   
'   |_ healthInsuranceAndPaymentInformation 0..1   
'     |_ healthInsuranceCode 0..1   
'     |_ healthInsuranceName 0..1   
'     |_ healthInsuranceNumber 0..1   
'   |_ intendedRecipient 0..*   
'   |_ authorship 1..*   
'     |_ author 1..1   
'     |_ datetime 1..1   
'   |_ attestation 0..*   
'     |_ attester 1..1   
'     |_ datetime 1..1   
'   |_ legalAuthentication 0..1   
'     |_ legalAuthenticator 1..1   
'     |_ datetime 1..1   
' }


' EHDSLaboratoryReportHeader -u-|> DocumentMetadata : extends
' EHDSLaboratoryReport o-u- EHDSLaboratoryReportHeader
' EHDSLaboratoryReport o-d- EHDSLaboratoryReportBody
' EHDSImagingReport o-u- EHDSImagingReportHeader
' EHDSImagingReport o-d- EHDSImagingReportBody : "  \n"
' EHDSImagingReportHeader -u-o ImgReportDocumentMetadata
' EHDSImagingReportHeader -d-o ContentMetadata
' EHDSLaboratoryReportHeader -d-o ContentMetadata
' DocumentMetadata -r[hidden]- ContentMetadata

' ImgReportDocumentMetadata -u-|> DocumentMetadata : extends
' EHDSImagingReport -r[hidden]- EHDSLaboratoryReport
' EHDSImagingReportHeader -r[hidden]- EHDSLaboratoryReportHeader

' EHDSImagingReportBody o-r- OrderInformation : "         "
' EHDSLaboratoryReportBody o-l- OrderInformation  : "         "

@enduml

