/*
Logical: EHDSPatientSummaryBody
//Id: EHDSpatientSummaryBody
Title: "Patient summary body model"
Description: """B.1 - EHDS refined base model for Patient Summary body data elements"""
Characteristics: #can-be-target

* alerts 1..1 Base "B.1.1 - Alerts" """Alert section includes information about allergies, intolerances and other substantial alerts or warnings that health professionals should be aware of. """
  * sectionNarative 0..1 string "B.1.1.1 - Section narative" """Narative content of the section. This narative shell containing either narative description of both allergy and alerts, or similar narative sub-section elements shell be provided.  """
  * allergy 1..* EHDSAllergyIntolerance "B.1.1.2 - Allergy" """A record of allergies and intolerances."""
  * medicalAlert 0..* EHDSAlertFlag "B.1.1.3 - Medical alert" """Medical alert information (other alerts not included in allergies)."""
* medicalHistory 1..1 Base "B.1.2 - Medical history" """Medical history section."""
  * sectionNarative 0..1 string "B.1.2.1 - Section narative" """Narative content of the section. This narative shell containing either narative description of al subsections, or similar narative sub-section elements shell be provided. This will be the preferred way.  """
  * vaccinationSection 0..1 Base "B.1.2.2 - Vaccination section" """Vaccination history subsection."""
    * subsectionNarative 0..1 string "B.1.2.2.1 - Subsection narative" """Narative content of the section. """
    * vaccination 0..* EHDSImmunisation "B.1.2.2.2 - Vaccination" """Vaccination / prophylaxis information."""
  * pastProblemsSection 0..1 Base "B.1.2.3 - Past problems section" """Problems history subsection."""
    * subsectionNarative 0..1 string "B.1.2.3.1 - Subsection narative" """Narative content of the subsection. """
    * pastProblems 0..* EHDSCondition "B.1.2.3.2 - Past problems" """Resolved, closed or inactive problems."""
  * medicalHistorySection 0..1 Base "B.1.2.4 - Medical history section" """Medical history section."""
    * medicalHistory 0..* string "B.1.2.4.1 - Medical history" """This section may provide both synthetic anamnesis (e.g. description of phases of the pathology as a chronological summary of clustered clinical information) and anecdotal evidence that clinicians can collect from the patient, and can read in a narrative form.See Section 2, Chapter III, Art 7, (c)."""
* medicalProblems 1..1 Base "B.1.3 - Medical problems" """Current medical problems section."""
  * sectionNarative 0..1 string "B.1.3.1 - Section narative" """Narative content of the section. """
  * currentProblemsSection 0..1 Base "B.1.3.2 - Current problems section" """Current problems section"""
    * subsectionNarative 0..1 string "B.1.3.2.1 - Subsection narative" """Narative content of the subsection. """
    * currentProblems 1..* EHDSCondition "B.1.3.2.2 - Current problems" """Health conditions affecting the health of the patient and are important to be known for a health professional during a health encounter."""
  * medicalDevicesAndImplantsSection 0..1 Base "B.1.3.3 - Medical devices and implants section" """Devices that are implanted in the patient and external medical devices and equipment that the
health status depends on."""
    * subsectionNarative 0..1 string "B.1.3.3.1 - Subsection narative" """Narative content of the subsection. """
    * medicalDevicesAndImplants 1..* EHDSDeviceUse "B.1.3.3.2 - Medical devices and implants" """Includes the patient's implanted and external medical devices and equipment upon which their health status depends. Includes devices such as cardiac pacemakers, implantable fibrillator, prosthesis, ferromagnetic bone implants, etc. of which the HP needs to be aware."""
  * proceduresSection 0..1 Base "B.1.3.4 - Procedures section" """Procedures section"""
    * subsectionNarative 0..1 string "B.1.3.4.1 - Subsection narative" """Narative content of the subsection. """
    * procedures 1..* EHDSProcedure "B.1.3.4.2 - Procedures" """Major procedures."""
  * functionalStatusSection 0..1 Base "B.1.3.5 - Functional status section" """Funtional assessment section"""
    * subsectionNarative 0..1 string "B.1.3.5.1 - Subsection narative" """Narative content of the subsection. """
    * functionalStatusAssessment 0..* EHDSFunctionalStatus "B.1.3.5.2 - Functional status assessment" """A record of a clinical assessment performed to determine what problem(s) may affect the patient and before planning the treatments or management strategies that are best to manage a patient's condition."""
* medicationSummary 1..1 Base "B.1.4 - Medication summary" """Medication summary section."""
  * sectionNarative 0..1 string "B.1.4.1 - Section narative" """Narative content of the section. """
  * currentAndRelevantPastMedicines 1..* EHDSMedicationStatement "B.1.4.2 - Current and relevant past medicines" """Relevant prescribed medicines whose period of time indicated for the treatment has not yet expired whether it has been dispensed or not, or medicines that influence current health status or are relevant to a clinical decision."""
* socialHistory 0..1 Base "B.1.5 - Social history" """Social history section."""
  * socialHistoryDescription 1..1 string "B.1.5.1 - Social history description" """Textual description of the socialhistory."""
  * socialHistoryObservationsRelatedToHealth 0..* EHDSObservation "B.1.5.2 - Social history observations related to health" """Health related lifestyle factors or lifestyle observations and social determinants of health. Example: cigarette smoker, alcohol consumption"""
    * referenceDateRange 0..* Period "B.1.5.2.1 - Reference date range" """Example: from 1974 to 2004"""
* pregnancyHistory 0..1 Base "B.1.6 - Pregnancy history" """Pregnancy history section"""
  * sectionNarative 0..1 string "B.1.6.1 - Section narative" """Narative content of the section. """
  * currentPregnancyStatus 0..1 Base "B.1.6.2 - Current pregnancy status" """Current pregnancy status section"""
    * dateOfObservation 0..* dateTime "B.1.6.2.1 - Date of observation" """Date on which the observation of the pregnancy state was made"""
    * status 0..* EHDSObservation "B.1.6.2.2 - Status" """Provides the woman's current state at the date the observation was made: e.g. pregnant, not pregnant, unknown"""
    * expectedDateOfDelivery 0..1 dateTime "B.1.6.2.3 - Expected date of delivery" """Date on which the woman is due to give birth."""
  * historyOfPreviousPregnancies 0..1 Base "B.1.6.3 - History of previous pregnancies" """History of previous pregnancies section"""
    * previousPregnanciesStatus 0..1 EHDSObservation "B.1.6.2.1 - Previous pregnancies status" """Information on the woman's previous pregnancies:Yes, previous pregnancies; No, previous pregnancies; Unknown"""
    * previousPregnanciesDescription 0..* Base "B.1.6.2.2 - Previous pregnancies description" """Details of the previous pregnancies"""
      * outcomeDate 0..1 dateTime "B.1.6.2.2.1 - Outcome date" """Date referred to the previous pregnancies outcome"""
      * outcome 0..1 EHDSObservation "B.1.6.2.2.2 - Outcome" """Outcome of the previous pregnancies"""
      * numberOfChildren 0..1 unsignedInt "B.1.6.2.2.3 - Number of children" """Number of children/fetus in this specific pregnancy"""
* patientProvidedData 0..1 Base "B.1.7 - Patient provided data" """Patient provided data section"""
  * sectionNarative 0..1 string "B.1.7.1 - Section narative" """Narative content of the section. """
  * travelHistory 0..* Base "B.1.7.2 - Travel history" """Visited country"""
    * country 0..1 CodeableConcept "B.1.7.2.1 - Country" """Country code"""
      * ^binding.description = "ISO 3166"
      * ^binding.strength = #preferred
    * period 0..* Period "B.1.7.2.2 - Period" """Date of entry and departure"""
  * advanceDirective 0..1 Base "B.1.7.3 - Advance Directive" """Advance directive section"""
    * documentation 0..* CodeableConcept "B.1.7.3.1 - Documentation" """Existence of documentation on living will"""
      * ^binding.description = "SNOMED CT"
      * ^binding.strength = #preferred
* results 0..1 Base "B.1.8 - Results" """Results section"""
  * sectionNarative 0..1 string "B.1.8.1 - Section narative" """Narative content of the section. """
  * resultObservation[x] 0..* EHDSObservation or EHDSLaboratoryObservation "B.1.8.2 - Result observation" """Observation results pertaining to the subject of care's health condition and which might have impact on future treatments"""
* planOfCare 0..1 Base "B.1.9 - Plan of Care" """Therapeutic recommendations that do not include pharmacologic treatments, such as diet, physical exercise, planned surgeries"""
  * description 0..1 string "B.1.9.1 - Description" """Narrative containing the plan including proposals, goals, and order requests for monitoring, tracking, or improving the condition of the patient.In the future it is expected that this Section could be provided in a structured and coded format."""
  * planOfCareEntry 0..* EHDSCarePlan "B.1.9.2 - Plan of Care Entry" """Describes the intention of how one or more practitioners intend to deliver care for a particular patient for a period of time, possibly limited to care for a specific condition or set of conditions."""
*/